## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
app_value_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace=app_value_counts[app_value_counts < 528].index
application_types_to_replace

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object')

In [ ]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_value_counts = application_df['CLASSIFICATION'].value_counts()

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print (class_value_counts[class_value_counts > 1])

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_value_counts[class_value_counts < 1883].index
classifications_to_replace

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object')

In [ ]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
ask_amt_value_counts = application_df['ASK_AMT'].value_counts()
print (ask_amt_value_counts[ask_amt_value_counts > 2])

KeyError: 'ASK_AMT'

In [ ]:
# Choose a cutoff value and create a list of ask amounts to be replaced
# use the variable name `ask_amts_to_replace`
ask_amts_to_replace = ask_amt_value_counts[ask_amt_value_counts < 25398].index

# Replace in dataframe
for ask_amt in ask_amts_to_replace:
    application_df['ASK_AMT'] = application_df['ASK_AMT'].replace(ask_amt,"Other")

# Check to make sure binning was successful
application_df['ASK_AMT'].value_counts()

5000     25398
Other     8901
Name: ASK_AMT, dtype: int64

In [ ]:
# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS',
 'ASK_AMT']

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df=pd.get_dummies(application_df, columns=application_cat, drop_first=True, dtype='int')

In [ ]:
application_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y,ASK_AMT_Other
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=35, stratify=y)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 8)                 296

 dense_4 (Dense)             (None, 5)                 45

 dense_5 (Dense)             (None, 1)                 6

=================================================================
Total params: 347 (1.36 KB)
Trainable params: 347 (1.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6206 - accuracy: 0.6864
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5890 - accuracy: 0.7003
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5763 - accuracy: 0.7023
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5683 - accuracy: 0.7029
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7126
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7243
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7236
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7250
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7257
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5575 - accuracy: 0.7264
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7280
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7271
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7277
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7292
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5542 - accuracy: 0.7294
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5535 - accuracy: 0.7300
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5535 - accuracy: 0.7306
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7296
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7297
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5526 - accuracy: 0.7303
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7301
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5516 - accuracy: 0.7315
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5515 - accuracy: 0.7309
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7303
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7304
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7306
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7310
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7308
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7308
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7313
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7309
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7312
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7309
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7314
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7318
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7317
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7322
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7308
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7311
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7309
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7309
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7328
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7315
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7325
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7317
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7321
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7310
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7326
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7313
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7319
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7312
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7316
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7316
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7316
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7322
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7319
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7321
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7320
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7315
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7328
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7323
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7320
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7322
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7325
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7324
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7327
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7322
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7320
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7314
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7320
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7316
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7325
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7327
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7322
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7325
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7327
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7326
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7331
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7329
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7333
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7325
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7326
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7328
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7331
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7326
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7338
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7333
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7324
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7341
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5469 - accuracy: 0.7332
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5470 - accuracy: 0.7339
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7346
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5468 - accuracy: 0.7327
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7340
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7332
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7332
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7328
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7333
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7337

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5494 - accuracy: 0.7289 - 415ms/epoch - 2ms/step
Loss: 0.5494136214256287, Accuracy: 0.728863000869751

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(